# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='_account',
        ),
        migrations.AddField(
            model_name='charge',
            name='_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
